graph TB

    subgraph "LAN"

        browser[Web Browser]

        subgraph "Node-RED"

            ui[UI]
            flows[Automation Flows]

        end

        groundFloorHueBridge[Ground Floor Hue Bridge]
        basementHueBridge[Basement Hue Bridge]
        powerviewHub[PowerView Hub]
        hueDevice1[Hue Devices]
        hueDevice2[Hue Devices]
        shades[Window Shades]

    end

    browser -- HTTP --- ui
    browser -- WebSocket --- flows
    ui -- WebSocket --- flows
    flows -- HTTP --- groundFloorHueBridge
    flows -- HTTP --- basementHueBridge
    flows -- HTTP --- powerviewHub
    groundFloorHueBridge -- Zigbee --- hueDevice1
    basementHueBridge -- Zigbee --- hueDevice2
    powerviewHub -- Zigbee --- shades
